#!/bin/sh

su danil \
   --shell=/bin/bash \
   --command '"$HOME"/.gvm/pkgsets/go1.5.1/global/bin/tgtm'

EXITVALUE=$?
if [ $EXITVALUE != 0 ]; then
    logger -t git "ALERT tweets mailing exited abnormally with [$EXITVALUE]"
fi

exit 0
