####
#
# /etc/sysctl.conf is meant for local sysctl settings
#
# sysctl reads settings from the following locations:
#   /boot/sysctl.conf-<kernelversion>
#   /lib/sysctl.d/*.conf
#   /usr/lib/sysctl.d/*.conf
#   /usr/local/lib/sysctl.d/*.conf
#   /etc/sysctl.d/*.conf
#   /run/sysctl.d/*.conf
#   /etc/sysctl.conf
#
# To disable or override a distribution provided file just place a
# file with the same name in /etc/sysctl.d/
#
# See sysctl.conf(5), sysctl.d(5) and sysctl(8) for more information
#
####

# Bind privileged port as non-root non-privileged user and fix error: `permission denied: 80`,
# <https://stackoverflow.com/questions/413807/is-there-a-way-for-non-root-processes-to-bind-to-privileged-ports-on-linux#51439516>,
# ~~~~<danil@kutkevich.org>.
net.ipv4.ip_unprivileged_port_start=0

# Limits/ulimit
# <https://cyberciti.biz/faq/linux-increase-the-maximum-number-of-open-files>,
# <https://wiki.archlinux.org/title/Limits.conf>,
# <https://medium.com/@muhammadtriwibowo/set-permanently-ulimit-n-open-files-in-ubuntu-4d61064429a>.
# ~~~~<danil@kutkevich.org>.
fs.file-max = 65535

# Increase the inotify limit to get filesystem watcher to work
# SyncThing/MEGAsync
# <https://docs.syncthing.net/users/faq.html#inotify-limits>
# <https://docs.syncthing.net/users/faq.html#inotify-limits>
# ~~~~<danil@kutkevich.org>.
fs.inotify.max_user_watches = 524288

# Ping fixing of error `socktype: SOCK_RAW: socket: Operation not permitted`
# ~~~~<danil@kutkevich.org>.
net.ipv4.ping_group_range = 0 2147483647
