#!/bin/sh

# Danil.
# Last sync time see in /usr/portage/metadata/timestamp
emerge --sync --quiet > /dev/null

EXITVALUE=$?
if [ $EXITVALUE != 0 ]; then
    logger -t portage "ALERT sync exited abnormally with [$EXITVALUE]"
fi

exit 0
