#!/bin/sh

# Danil.
emerge --sync --quiet && \
    layman --sync-all --quiet && \
    eix-update --quiet 2>&1

EXITVALUE=$?
if [ $EXITVALUE != 0 ]; then
    logger -t portage "ALERT sync exited abnormally with [$EXITVALUE]"
fi

echo "$(date)" > /portage
exit 0
