# Limits/ulimit
# <https://cyberciti.biz/faq/linux-increase-the-maximum-number-of-open-files>,
# <https://wiki.archlinux.org/title/Limits.conf>.
# ~~~~<danil@kutkevich.org>.
* hard nofile 65535
* soft nofile 65535
